language: rust
sudo: false

script:
  - cargo build --verbose && cargo test --verbose && cargo doc --verbose
after_success:
  - test "$TRAVIS_PULL_REQUEST" == false && test "$TRAVIS_BRANCH" == "master" && bash deploy-docs.sh
env:
  global:
    secure: DGTtHe0QLG+WuuBqdIev9Pe2xbWHsKJd1mWIG/6tYoKAzReYaUCFrLn7UpbWI9VFoOYVzn/0WdgMUu0eDuZKz1DieqllaGDHkoOQe5w7pc4ro65kicRRYew8GAJeDS1QqEiz2dDyhF8ZRnigaKb+l7nqmMdMpUJF3xmXB7GK2+s=
notifications:
    webhooks: http://huon.me:54856/travis
